module.exports = {
  meta: {
    date: new Date().toISOString(),
    format: 'Modern',
    totalDecks: 1847,
    totalEvents: 42,
    archetypes: [
      { name: 'Murktide Regent', nameCN: '墨鳕帝君', share: 9.2, sampleSize: 170, tier: 'S', keyCards: ['Murktide Regent', "Ragavan, Nimble Pilferer", "Dragon's Rage Channeler"], price: 1200 },
      { name: 'Living End', nameCN: '活终末', share: 7.8, sampleSize: 144, tier: 'S', keyCards: ['Living End', 'Architects of Will', 'Street Wraith'], price: 800 },
      { name: 'Amulet Titan', nameCN: '护符泰坦', share: 6.5, sampleSize: 120, tier: 'A', keyCards: ['Primeval Titan', 'Amulet of Vigor', 'Dryad of the Ilysian Grove'], price: 900 },
      { name: 'Yawgmoth', nameCN: '约格莫夫', share: 5.9, sampleSize: 109, tier: 'A', keyCards: ['Yawgmoth, Thran Physician', 'Young Wolf', "Geralf's Messenger"], price: 850 },
      { name: 'Rakdos Scam', nameCN: '拉铎斯骗局', share: 5.4, sampleSize: 100, tier: 'A', keyCards: ['Grief', 'Fury', 'Malakir Rebirth'], price: 1100 },
      { name: 'Hammer Time', nameCN: '铁锤时间', share: 4.8, sampleSize: 89, tier: 'A', keyCards: ['Colossus Hammer', 'Puresteel Paladin', 'Stoneforge Mystic'], price: 700 },
      { name: 'Creativity', nameCN: '创造力', share: 4.2, sampleSize: 78, tier: 'B', keyCards: ['Indomitable Creativity', 'Archon of Cruelty', 'Wrenn and Six'], price: 1400 },
      { name: 'Mono G Tron', nameCN: '单色绿创', share: 3.8, sampleSize: 70, tier: 'B', keyCards: ['Karn Liberated', 'Ugin, the Spirit Dragon', 'Ancient Stirrings'], price: 600 },
      { name: 'Burn', nameCN: '红烧', share: 3.5, sampleSize: 65, tier: 'B', keyCards: ['Lightning Bolt', 'Goblin Guide', 'Lava Spike'], price: 400 },
      { name: 'Affinity', nameCN: '神器共鸣', share: 3.1, sampleSize: 57, tier: 'B', keyCards: ["Urza's Saga", 'Thought Monitor', 'Ornithopter'], price: 750 },
      { name: 'Jund', nameCN: '勇得', share: 2.7, sampleSize: 50, tier: 'B', keyCards: ['Liliana of the Veil', 'Bloodbraid Elf', 'Ragavan'], price: 1300 },
      { name: 'Merfolk', nameCN: '人鱼', share: 2.4, sampleSize: 44, tier: 'C', keyCards: ['Lord of Atlantis', 'Aether Vial', 'Force of Negation'], price: 900 },
      { name: 'Dredge', nameCN: '掘坟', share: 2.1, sampleSize: 39, tier: 'C', keyCards: ['Cathartic Reunion', 'Life from the Loam', 'Narcomoeba'], price: 500 },
      { name: 'Heliod Combo', nameCN: '赫利欧德组合技', share: 1.9, sampleSize: 35, tier: 'C', keyCards: ['Heliod, Sun-Crowned', 'Walking Ballista', 'Spike Feeder'], price: 650 },
      { name: 'Grixis Shadow', nameCN: '格里西斯影身', share: 1.7, sampleSize: 31, tier: 'C', keyCards: ["Death's Shadow", 'Ragavan', 'Dress Down'], price: 1100 },
    ],
    trends: [
      { archetype: 'Murktide Regent', shareChange: -0.8, winRateChange: -1.2 },
      { archetype: 'Living End', shareChange: 1.5, winRateChange: 2.3 },
      { archetype: 'Amulet Titan', shareChange: 0.3, winRateChange: -0.5 },
      { archetype: 'Yawgmoth', shareChange: 2.1, winRateChange: 3.4 },
      { archetype: 'Rakdos Scam', shareChange: -1.2, winRateChange: -2.1 },
    ],
  },
  players: [
    { id: 'aspiringspike', name: 'Aspiring Spike', elo: 1875, eloRank: 1, winRate: 64.2, matchesPlayed: 342, recentEvents: [], archetypes: ['Amulet Titan', 'Creativity'] },
    { id: 'kanister', name: 'kanister', elo: 1843, eloRank: 2, winRate: 62.8, matchesPlayed: 518, recentEvents: [], archetypes: ['Yawgmoth', 'Amulet Titan'] },
    { id: 'mengu', name: 'Mengu', elo: 1821, eloRank: 3, winRate: 61.5, matchesPlayed: 289, recentEvents: [], archetypes: ['Murktide Regent', 'Rakdos Scam'] },
    { id: 'yowza', name: 'Yowza', elo: 1809, eloRank: 4, winRate: 60.9, matchesPlayed: 198, recentEvents: [], archetypes: ['Hammer Time', 'Affinity'] },
    { id: 'thurule', name: 'Thurule', elo: 1795, eloRank: 5, winRate: 59.8, matchesPlayed: 267, recentEvents: [], archetypes: ['Living End', 'Creativity'] },
    { id: 'trellon', name: 'Trellon', elo: 1788, eloRank: 6, winRate: 59.2, matchesPlayed: 156, recentEvents: [], archetypes: ['Burn', 'Mono G Tron'] },
    { id: 'nathansteuer', name: 'Nathan Steuer', elo: 1782, eloRank: 7, winRate: 58.7, matchesPlayed: 401, recentEvents: [], archetypes: ['Rakdos Scam', 'Jund'] },
    { id: 'burnt-taco', name: 'Burnt Taco', elo: 1776, eloRank: 8, winRate: 58.1, matchesPlayed: 223, recentEvents: [], archetypes: ['Yawgmoth', 'Heliod Combo'] },
    { id: 'dominator', name: 'Dominator', elo: 1769, eloRank: 9, winRate: 57.5, matchesPlayed: 312, recentEvents: [], archetypes: ['Dredge', 'Living End'] },
    { id: 'masonclark', name: 'Mason Clark', elo: 1761, eloRank: 10, winRate: 56.9, matchesPlayed: 445, recentEvents: [], archetypes: ['Murktide Regent', 'Grixis Shadow'] },
  ],
};
